# Generated by Django 5.2.7 on 2025-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_features_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_features', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='About_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_info1', models.CharField(max_length=200)),
                ('about_info2', models.CharField(max_length=200)),
                ('about_img', models.ImageField(default=None, null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='BookOrder_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('select_book', models.CharField(choices=[('Learn HTML & CSS', 'Learn HTML & CSS'), ('JavaScript Essentials', 'JavaScript Essentials'), ('Mastering Photoshop', 'Mastering Photoshop'), ('UI/UX Design Guide', 'UI/UX Design Guide'), ('Illustrator for Beginners', 'Illustrator for Beginners')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Cash On Delivery', 'Cash On Delivery'), ('Credit/Debit Card', 'Credit/Debit Card')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact_form_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contact_map_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=100)),
                ('contact_map', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_Categories_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_categories_img1', models.ImageField(default=None, null=True, upload_to='static/img')),
                ('courses_categories_img2', models.ImageField(default=None, null=True, upload_to='static/img')),
                ('courses_categories_img3', models.ImageField(default=None, null=True, upload_to='static/img')),
                ('courses_categories_img4', models.ImageField(default=None, null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_image', models.ImageField(default=None, null=True, upload_to='static/img')),
                ('courses_price', models.IntegerField()),
                ('courses_rating', models.IntegerField(default=5)),
                ('courses_rating_count', models.IntegerField()),
                ('courses_title', models.CharField(max_length=200)),
                ('courses_instructor', models.CharField(max_length=100)),
                ('courses_duration', models.CharField(max_length=20)),
                ('courses_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_team_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_team_img', models.ImageField(default=None, null=True, upload_to='static/img')),
                ('our_team_f_link', models.CharField(max_length=100)),
                ('our_team_t_link', models.CharField(max_length=100)),
                ('our_team_i_link', models.CharField(max_length=100)),
                ('our_team_name', models.CharField(max_length=100)),
                ('our_team_destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('image', models.ImageField(default=None, null=True, upload_to='static/img')),
            ],
        ),
    ]
