# Generated by Django 5.2.7 on 2025-11-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLEARNING_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_categories_tbl',
            name='courses_name1',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='courses_categories_tbl',
            name='courses_name2',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='courses_categories_tbl',
            name='courses_name3',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='courses_categories_tbl',
            name='courses_name4',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
