# Generated by Django 5.2.7 on 2025-11-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLEARNING_app', '0002_courses_categories_tbl_courses_name1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coureses_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_list1', models.CharField(max_length=100)),
                ('courses_list2', models.CharField(max_length=100)),
                ('courses_list3', models.CharField(max_length=100)),
                ('courses_list4', models.CharField(max_length=100)),
            ],
        ),
    ]
