# Generated by Django 5.2.7 on 2025-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLEARNING_app', '0004_coureses_list_tbl_delete_coureses_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_info', models.CharField(max_length=500)),
                ('card_icon', models.CharField(max_length=100)),
            ],
        ),
    ]
