# Generated by Django 5.2.7 on 2025-12-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLEARNING_app', '0005_about_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial_tbl',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='testimonial_tbl',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial_tbl',
            name='message',
        ),
        migrations.RemoveField(
            model_name='testimonial_tbl',
            name='profession',
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='client_name1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='client_name2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='client_name3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='message1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='message2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='message3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='profession1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='profession2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonial_tbl',
            name='profession3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
