# Generated by Django 5.2.7 on 2025-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLEARNING_app', '0006_remove_testimonial_tbl_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carousel_title', models.CharField(max_length=200)),
                ('Carousel_subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('Carousel_description', models.CharField(max_length=500)),
                ('Carousel_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='About_Carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Carousel_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Carousel_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_Carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Courses_Carousel_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Carousel_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Carousel_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial_Carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonial_Carousel_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/img')),
            ],
        ),
    ]
