# Generated by Django 5.2.7 on 2025-12-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLEARNING_app', '0007_about_carousel_about_carousel_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_carousel_img',
            old_name='Contact_Carousel_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='order_carousel_img',
            old_name='Order_Carousel_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='testimonial_carousel_img',
            old_name='Testimonial_Carousel_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='about_carousel_img',
            name='About_Carousel_image',
        ),
        migrations.RemoveField(
            model_name='courses_carousel_img',
            name='Courses_Carousel_image',
        ),
        migrations.RemoveField(
            model_name='team_carousel_img',
            name='Team_Carousel_image',
        ),
        migrations.AddField(
            model_name='about_carousel_img',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='courses_carousel_img',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='team_carousel_img',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img'),
        ),
    ]
